language: ruby
before_install:
  - gem update --system
  - gem --version
install:
  - gem install bundler:2.3.8
script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:create
services:
  - redis-server

