language: ruby
rvm:
    - 2.5.9
before_install:
    - gem update --system
    - gem --version
install: gem install bundler -v 2.2.20
script:
    - bundle install
    - bundle exec rake db:migrate RAILS_ENV=test
services:
    - redis-server

