language: ruby
rvm:
    - 2.3.7
before_install:
    - gem update --system
    - gem --version
install: gem install rails
script:
    - bundle install
    - bundle exec rake db:migrate RAILS_ENV=test
services:
    - redis-server

