language: ruby
rvm:
    - 2.3.4
    - jruby
before_install:
    - gem update --system
    - gem --version
install: gem install rails
script:
    - bundle exec rails db:migrate RAILS_ENV=test
    - bundle exec rspec
services:
    - redis-server

